### ISSUE TITLE
Storage >> Stored Items >> error when trying to view XXL list of NFTs in an NFT Collection

### ISSUE THREAD

**Issue by ghost** [33-Labs/Floview#3]
When clicking on the "Show Detail" button for an account that has a very large number of NFTs (25k+) it crashes the browser.

For example:
https://www.flowview.app/account/0x921ea449dffec68a/storage/FlovatarComponentCollection

The browser becomes unresponsive and eventually shows this:
`Application error: a client-side exception has occurred (see the browser console for more information).`

And in the console:
`RangeError: Maximum call stack size exceeded`

Perhaps it could generate aa JSON file of the list behind the scenes and then send the file to the browser to download? Or incrementally populate the textarea as the response is received?

**Comment by LanfordCai** [comment]
@derp-derp-derp Thank you for your feedback!

I have added a download button, could you have a try?
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/10380321/230769235-437cf827-01d8-455a-8dd9-08e9b34bb834.png">

**Comment by ghost** [comment]
It works great! Nicely done. Thank you!

**Comment by ghost** [comment]
@LanfordCai This worked for a long time but is now returning an empty object `{}` in the example I linked originally:
https://www.flowview.app/account/0x921ea449dffec68a/storage/FlovatarComponentCollection

**Comment by LanfordCai** [comment]
@derp-derp-derp Sorry, this collection is too large now and it can't be returned. You can check the discussion here: https://discord.com/channels/613813861610684416/1186707071899545672

**Comment by ghost** [comment]
@LanfordCai Thank you. That's a bummer.
