### ISSUE TITLE
Add HybridCustody child/owned accounts view

### ISSUE THREAD

**Issue by sisyphusSmiling** [33-Labs/Floview#4]
## Description

Add an account view component that lists an address's child and owned account addresses. May also resolve the `MetadataViews.Display` included in either/both `OwnedAccount.display` or/and `ChildAccount.display` as defined in the `HybridCustody` contract.

## Reference

Below are some queries that might help resolve the child account addresses and app-defined `Display` views.

Note that `ChildAccount.display` is settable by the parent while `OwnedAccount.display` is settable by the owner of the child account, at least in the current construction. Being able to see child & owned account addresses would be helpful enough on its own and avoid any thrash created by changes made to metadata access patterns while finalizing.

- [get_child_addresses.cdc script](https://github.com/onflow/hybrid-custody/blob/main/scripts/hybrid-custody/get_child_addresses.cdc)
- [resolve_owned_display_name.cdc](https://github.com/onflow/hybrid-custody/blob/main/scripts/hybrid-custody/metadata/resolve_owned_display_name.cdc)

`get_owned_addresses.cdc` is in [PR](https://github.com/onflow/hybrid-custody/pull/116) atm, but pretty similar to retrieving child addresses.

**Comment by LanfordCai** [comment]
Haha, I had a similar thought before, but after submitting a PR for [linked-accounts](https://github.com/onflow/linked-accounts), I realized that the project is still under active development and there could be many changes happening. So I decided to wait until it goes live on the mainnet before adding support. Is the project stable now?

**Comment by sisyphusSmiling** [comment]
The new repo location is [onflow/hybrid-custody](https://github.com/onflow/hybrid-custody) (thanks for reminding me I should add a disclaimer in the linked-accounts README!) and is still undergoing changes before another testnet deployment - ETA by EOW next week at the latest. That said, the interface for discovering child and owned account addresses is stable

**Comment by LanfordCai** [comment]
Great! Will start this after submitting the Hackathon project!

**Comment by LanfordCai** [comment]
@sisyphusSmiling Please take a look at https://flowview.app and give me some feedback
