### ISSUE TITLE
Flowview is showing old account information on Testnet (and possibly Mainnet)

### ISSUE THREAD

**Issue by rich-baker-clearskyconcepts** [33-Labs/Floview#5]
This was noticed in the deployed version of Flowview.

When deploying Flowview locally and configuring for Testnet, the same is noticed as well.  However when changing the ACCESS_API endpoint locally in the .env.development file to the latest Quiknode Testnet REST endpoint recently advertised by Dapper Labs on the Flow Discord developer-updates channel, it shows the latest information for the account.

Did not check Mainnet, but the same may be true there as well.

You may want to update your deployed Flowview configuration to use these latest Quiknode ACCESS_API endpoints recently advertised by Dapper Labs:

**Testnet**
gRPC: side-still-sanctuary.flow-testnet.quiknode.pro:9000
Web gRPC: https://side-still-sanctuary.flow-testnet.quiknode.pro/grpc-web
**REST: https://side-still-sanctuary.flow-testnet.quiknode.pro**

**Mainnet**
gRPC: floral-special-valley.flow-mainnet.quiknode.pro:9000
Web gRPC: https://floral-special-valley.flow-mainnet.quiknode.pro/grpc-web
**REST: https://floral-special-valley.flow-mainnet.quiknode.pro**

**Comment by LanfordCai** [comment]
Thank you! I have switched to QuickNode APIs
